# Generated by Django 4.1.3 on 2022-11-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210910_1332'),
        ('api', '0003_room_current_song'),
    ]

    operations = [
    ]
